# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_password_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
