# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='0000-00-00'),
            preserve_default=False,
        ),
    ]
