# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20190725_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
